In [2]:
import numpy as np

def squareWave(d,size,shift=0):
    out = np.empty([size], dtype='bool')
    for index in range(size):

        shiftedIndex = (index + shift)%size
        out[shiftedIndex] = ((index*d)%size <size/2)
    return out

In [3]:
def boolArraytoUint(arrayIn):
    i=1
    res = 0
    for x in arrayIn:
        if x : res+=i
        i=i*2
    return res

In [4]:
def valuetable(arrayIn):
    r,c = arrayIn.shape
    out = np.empty([c], dtype='int')
    for index in range(c):
      out[index] = boolArraytoUint(arrayIn[:,index])

    return out

In [5]:
squareWave(5,30)

array([ True,  True,  True, False, False, False,  True,  True,  True,
       False, False, False,  True,  True,  True, False, False, False,
        True,  True,  True, False, False, False,  True,  True,  True,
       False, False, False])

In [6]:
waves = np.array([squareWave(1,30),np.logical_not(squareWave(3,30)),np.logical_not(squareWave(5,30))])

In [7]:
waves

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False],
       [False, False, False, False, False,  True,  True,  True,  True,
         True, False, False, False, False, False,  True,  True,  True,
         True,  True, False, False, False, False, False,  True,  True,
         True,  True,  True],
       [False, False, False,  True,  True,  True, False, False, False,
         True,  True,  True, False, False, False,  True,  True,  True,
        False, False, False,  True,  True,  True, False, False, False,
         True,  True,  True]])

In [ ]:
boolArraytoUint(waves[:,0])

In [9]:
valuetable(waves)

array([1, 1, 1, 5, 5, 7, 3, 3, 3, 7, 5, 5, 1, 1, 1, 6, 6, 6, 2, 2, 0, 4,
       4, 4, 0, 2, 2, 6, 6, 6])