In [2]:
import numpy as np

def squareWave(d,size,shift=0):
    out = np.empty([size], dtype='bool')
    for index in range(size):

        shiftedIndex = (index + shift)%size
        out[shiftedIndex] = ((index*d)%size <size/2)
    return out

In [3]:
def boolArraytoUint(arrayIn):
    i=1
    res = 0
    for x in arrayIn:
        if x : res+=i
        i=i*2
    return res

In [4]:
def valuetable(arrayIn):
    r,c = arrayIn.shape
    out = np.empty([c], dtype='int')
    for index in range(c):
      out[index] = boolArraytoUint(arrayIn[:,index])

    return out

In [5]:
squareWave(5,30)

array([ True,  True,  True, False, False, False,  True,  True,  True,
       False, False, False,  True,  True,  True, False, False, False,
        True,  True,  True, False, False, False,  True,  True,  True,
       False, False, False])

In [6]:
wavesA = np.array([squareWave(1,30),np.logical_not(squareWave(3,30)),np.logical_not(squareWave(5,30))])
wavesB = np.array([squareWave(1,30,8),np.logical_not(squareWave(3,30,8)),np.logical_not(squareWave(5,30,8))])

In [9]:
A= valuetable(wavesA)
B = valuetable(wavesB)

In [11]:
A

array([1, 1, 1, 5, 5, 7, 3, 3, 3, 7, 5, 5, 1, 1, 1, 6, 6, 6, 2, 2, 0, 4,
       4, 4, 0, 2, 2, 6, 6, 6])

In [12]:
B

array([4, 4, 0, 2, 2, 6, 6, 6, 1, 1, 1, 5, 5, 7, 3, 3, 3, 7, 5, 5, 1, 1,
       1, 6, 6, 6, 2, 2, 0, 4])

In [56]:
def pio_code(A,B):
  strOut =""
  i=0
  while i < len(A):
    delay = " "
    if i < len(A)-1:
      if (A[i] == A[i+1]) & (B[i] == B[i+1]):
        delay = "[1]"
        i += 1
      else:  delay = ""
    strOut = strOut + "set pins, " +"0b{0:03b}".format(A[i]) + " \tside " + "0b{0:03b}".format(B[i]) + " " + delay + "\n"
    i += 1
  return strOut

In [57]:
pio_code(A,B)

'set pins, 0b001 \tside 0b100 [1]\nset pins, 0b001 \tside 0b000 \nset pins, 0b101 \tside 0b010 [1]\nset pins, 0b111 \tside 0b110 \nset pins, 0b011 \tside 0b110 [1]\nset pins, 0b011 \tside 0b001 \nset pins, 0b111 \tside 0b001 \nset pins, 0b101 \tside 0b001 \nset pins, 0b101 \tside 0b101 \nset pins, 0b001 \tside 0b101 \nset pins, 0b001 \tside 0b111 \nset pins, 0b001 \tside 0b011 \nset pins, 0b110 \tside 0b011 [1]\nset pins, 0b110 \tside 0b111 \nset pins, 0b010 \tside 0b101 [1]\nset pins, 0b000 \tside 0b001 \nset pins, 0b100 \tside 0b001 [1]\nset pins, 0b100 \tside 0b110 \nset pins, 0b000 \tside 0b110 \nset pins, 0b010 \tside 0b110 \nset pins, 0b010 \tside 0b010 \nset pins, 0b110 \tside 0b010 \nset pins, 0b110 \tside 0b000 \nset pins, 0b110 \tside 0b100  \n'